name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print hellow world
        run: echo "Hellow world"
      - name: print goodbye
        run: echo "Done - goodbye!"
